making slicing more pythonic
sunpy/cube pull request #22
Opened 2017-07-16 05:17 UTC by abit2

This way it makes cube_sequence.index_as_cube[0:5] possible which is much better than cube_sequence.index_as_cube[slice(0,5)].
@DanRyanIrish

2017-07-16 05:17 UTC, pep8speaks commented
Hello @abit2! Thanks for submitting the PR.

 - In the file [`sunpycube/cube/datacube.py`](https://github.com/sunpy/cube/blob/bbb4b100fdd84e354a80d7592224d82b44a842f9/sunpycube/cube/datacube.py), following are the PEP8 issues :

> [Line 82:80](https://github.com/sunpy/cube/blob/bbb4b100fdd84e354a80d7592224d82b44a842f9/sunpycube/cube/datacube.py#L82): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 79 characters)
> [Line 102:80](https://github.com/sunpy/cube/blob/bbb4b100fdd84e354a80d7592224d82b44a842f9/sunpycube/cube/datacube.py#L102): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (83 > 79 characters)
> [Line 135:80](https://github.com/sunpy/cube/blob/bbb4b100fdd84e354a80d7592224d82b44a842f9/sunpycube/cube/datacube.py#L135): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (83 > 79 characters)
> [Line 152:80](https://github.com/sunpy/cube/blob/bbb4b100fdd84e354a80d7592224d82b44a842f9/sunpycube/cube/datacube.py#L152): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (88 > 79 characters)
> [Line 170:80](https://github.com/sunpy/cube/blob/bbb4b100fdd84e354a80d7592224d82b44a842f9/sunpycube/cube/datacube.py#L170): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (85 > 79 characters)
> [Line 171:80](https://github.com/sunpy/cube/blob/bbb4b100fdd84e354a80d7592224d82b44a842f9/sunpycube/cube/datacube.py#L171): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (82 > 79 characters)
> [Line 173:80](https://github.com/sunpy/cube/blob/bbb4b100fdd84e354a80d7592224d82b44a842f9/sunpycube/cube/datacube.py#L173): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (82 > 79 characters)
> [Line 174:80](https://github.com/sunpy/cube/blob/bbb4b100fdd84e354a80d7592224d82b44a842f9/sunpycube/cube/datacube.py#L174): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (82 > 79 characters)
> [Line 175:80](https://github.com/sunpy/cube/blob/bbb4b100fdd84e354a80d7592224d82b44a842f9/sunpycube/cube/datacube.py#L175): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (80 > 79 characters)
> [Line 551:80](https://github.com/sunpy/cube/blob/bbb4b100fdd84e354a80d7592224d82b44a842f9/sunpycube/cube/datacube.py#L551): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (84 > 79 characters)
> [Line 552:80](https://github.com/sunpy/cube/blob/bbb4b100fdd84e354a80d7592224d82b44a842f9/sunpycube/cube/datacube.py#L552): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (82 > 79 characters)
> [Line 553:80](https://github.com/sunpy/cube/blob/bbb4b100fdd84e354a80d7592224d82b44a842f9/sunpycube/cube/datacube.py#L553): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (80 > 79 characters)
> [Line 554:80](https://github.com/sunpy/cube/blob/bbb4b100fdd84e354a80d7592224d82b44a842f9/sunpycube/cube/datacube.py#L554): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (82 > 79 characters)
> [Line 613:80](https://github.com/sunpy/cube/blob/bbb4b100fdd84e354a80d7592224d82b44a842f9/sunpycube/cube/datacube.py#L613): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (85 > 79 characters)
> [Line 619:4](https://github.com/sunpy/cube/blob/bbb4b100fdd84e354a80d7592224d82b44a842f9/sunpycube/cube/datacube.py#L619): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 639:80](https://github.com/sunpy/cube/blob/bbb4b100fdd84e354a80d7592224d82b44a842f9/sunpycube/cube/datacube.py#L639): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (85 > 79 characters)

2017-07-16 15:14 UTC, DanRyanIrish requested changes

2017-07-16 15:14 UTC, DanRyanIrish commented on sunpycube/cube/datacube.py
> +    """Helper class to make slicing in index_as_cube more pythonic"""
Can you be a little more explicit in you docstring?  Imagine documenting it so one of the IRIS team members, who haven't been following the details of our development, can get a idea of what the purpose of this helper is and how it works.

2017-07-16 15:14 UTC, DanRyanIrish commented on sunpycube/cube/datacube.py
> +    def index_as_cube(self):
Could you include an example in this docstring of how this function should be used?

2017-07-16 15:14 UTC, DanRyanIrish commented on sunpycube/cube/datacube.py
> +        self.seq = seq
Can you also explain in a comment or docstring what ```seq``` is?  Just a line should do.

2017-07-16 15:14 UTC, DanRyanIrish commented on sunpycube/cube/datacube.py
> +    def __getitem__(self, item):
Either here or in one of the docstrings above can you list the different allowed types that item can take?

2017-07-16 15:16 UTC, DanRyanIrish commented
Hi @abit2.  It's great you've already made headway with this.  Just left some comments to improve the documentation so someone else (or our future selves!) can easily see what is going on here.  Great work so far!

2017-07-16 16:53 UTC, DanRyanIrish commented
Regarding the helper class name, yeah it's tough to come up with a good one.  ```IndexAsCubeSlicer```?  Any other thoughts?  @Cadair?  This class should probably be "hidden" as well.  No need for typical users to see it.  So if the name is as above, it should actually be ```_IndexAsCubeSlicer```

2017-07-17 15:12 UTC, abit2 commented
@DanRyanIrish updated :)

2017-07-17 15:50 UTC, DanRyanIrish approved these changes

2017-07-17 15:50 UTC, merged